### PR TITLE
Updated Inventory to be Item

### PR DESCRIPTION
**Pull request by eugenelim97**
Now quantity can be shown on the UI. Command is:
inv add -name [name] -qty [qty] -unit [unit]

if unfilled, it will be 0.

### CODE REVIEW

**Comment by liujiajun** [comment]
Merged. Can you remove unit in later pr as we discussed?

**Comment by eugenelim97** [comment]
Ok sure. So String unit will be changed to String remarks in the Ingredient class am I right?

**Comment by liushiru** [comment]
Yes, I think so

**Comment by liushiru** [comment]
Can I remove Ingredient class under commons package and import model.Inventory.Ingredient?

**Pull request merged**
